In [19]:
import dill
import os.path
import numpy as np
if os.path.exists("notebook_session.db"):
    dill.load_session("notebook_session.db")
    print("workspace loaded.")

workspace loaded.


In [36]:
RandomMatrix1 = np.random.rand(3,3)
RandomMatrix2 = np.random.rand(3,1)

Results = RandomMatrix1@RandomMatrix2
dill.dump_session("notebook_session1.db")

In [37]:
print("The Computational Results: ")
print(Results)
Bruh = RandomMatrix2 = np.random.rand(3,3,3)
dill.dump_session("notebook_session2.db")

The Computational Results: 
[[0.6382207 ]
 [0.63364883]
 [1.05095591]]


In [39]:
dill.load_session("notebook_session2.db")
print(Results)
print(Bruh)

[[0.6382207 ]
 [0.63364883]
 [1.05095591]]
[[[0.42906278 0.86066286 0.11481676]
  [0.7772453  0.82956905 0.11017421]
  [0.25110657 0.86481139 0.06390998]]

 [[0.22205384 0.48240012 0.17963963]
  [0.90893602 0.73909302 0.7004263 ]
  [0.83295708 0.80223434 0.44592755]]

 [[0.19736255 0.46785242 0.02921231]
  [0.50993974 0.0042817  0.87527903]
  [0.49298818 0.422945   0.09651046]]]
