In [39]:
import numpy as np
sign = np.sign
eye = np.identity
np.set_printoptions(precision=4)


So, let's first of all, take a look at the Householder Reflector

In [2]:
v = np.array([[1], [1]])

The $v$ vector will defines a perpendicular hyper plane which is going to be the reflector, in this case, the reflection plane is just the vector $(-1, 1)$, which lies in the reflection plane. 

In [14]:
P = (eye(2) - 2*(v@v.conj().T)/(v.conj().T@v))
print(P)

[[ 0. -1.]
 [-1.  0.]]


As we can see that the matrix indeed performs a reflection operations on vectors, and the plane of reflection is (-1, 1); by the way, it's a reflector but it's also a projector, it's just different interpretation on the same thing. 

In [51]:
def reflect(x, y):
    """
        projection matrix that project the x onto the plane y lines in.
        :param x: 
            Column vector 
        :param y: 
            Column vector
    """
    if len(x.shape) == 2 and len(y.shape) == 2:
        y = (y.conj().T@y)*y
        v = -sign(x[0])*y - x
        return (eye(2) - 2*(v@v.conj().T)/(v.conj().T@v))
    else:
        return None
    
def hyperplane_reflect(v):
    """
        Given the vector v, the orthogonal vector the hyperplane, this will produce a reflection that reflects 
        vector with this hyperplane 
        :para v:
            The v vector will have to be a column vector. 
    """
    

Now let's try this out with our vector

In [50]:

P = reflect(np.array([[1], [1]]), np.array([[1], [0]]))
print(P)
print(P@np.array([[1], [1]]))

[[-0.6 -0.8]
 [-0.8  0.6]]
[[-1.4]
 [-0.2]]


In [43]:
len(np.array([1,2,3 ]).shape)


1